#!/bin/bash

echo -e "\n\
\n\
batch.grid.cyf-kr.edu.pl: \n\
                                                                         Req'd  Req'd   Elap\n\
Job ID               Username    Queue    Jobname          SessID NDS   TSK    Memory Time  S Time\n\
-------------------- ----------- -------- ---------------- ------ ----- ------ ------ ----- - -----\n\
56421949.batch.g     plgjliput   plgrid   STDIN               --      1      1    --  01:00 Q   -- \n\
\n"